global:
  imageRegistry: "eu.gcr.io/"
  imagePullSecrets:
    - name: registry-secret

frontend:
  replicaCount: 5

  image:
    tag: "v1.0.0"
    pullPolicy: IfNotPresent

  env:
    NODE_ENV: production
    VITE_API_URL: "https://api.mieszkaniownik.wsparcie.dev"
    VITE_GOOGLE_MAPS_API_KEY: "${VITE_GOOGLE_MAPS_API_KEY}"
    VITE_ENABLE_DEBUG: "false"
    VITE_LOG_LEVEL: "error"

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

config:
  api:
    baseUrl: "https://api.mieszkaniownik.wsparcie.dev"
    timeout: 30000
  features:
    enableAnalytics: true
    enableNotifications: true
    enableDarkMode: true
    enableDebugMode: false

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://api.mieszkaniownik.wsparcie.dev"
  hosts:
    - host: mieszkaniownik.wsparcie.dev
      paths:
        - path: /
          pathType: Prefix
          service: frontend
  tls:
    - secretName: mieszkaniownik-prod-tls
      hosts:
        - mieszkaniownik.wsparcie.dev

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 101
  fsGroup: 101

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 101
  capabilities:
    drop:
      - ALL

networkPolicy:
  enabled: true
